name = "Lean CAP game"
version = "1.0.0"
extra_files = "extras"
intro = "src/intro.lean"

[[worlds]]
name = "Intro"
id = 1
levels = [
	"src/group_theory/level_commutator.lean",
	"src/group_theory/level_commutator_2.lean",
	"src/group_theory/level_commutator_3.lean",
	# "src/basics/level2.lean",
]

[[worlds]]
name = "Tactics"
id = 2
parents = [1]
levels = [
	"src/group_theory/level1.lean",
	# "src/group_theory/level2.lean",
]
