name = "Lean CAP game"
version = "1.0.0"
extra_files = "extras"
intro = "src/intro.lean"

[[worlds]]
name = "Basics"
id = 1
levels = [
	"src/basics/level1.lean",
	"src/basics/level2.lean",
]

[[worlds]]
name = "Group theory"
id = 2
parents = [1]
levels = [
	"src/group_theory/level1.lean",
	"src/group_theory/level2.lean",
]
